# syntax=docker/dockerfile:1

ARG NODE_VERSION=18
ARG PNPM_VERSION=9.0.4

# Use node image for base image for all stages.
FROM  node:${NODE_VERSION}-alpine as base


# Set working directory for all build stages.
WORKDIR /usr/src/app

# Install pnpm.
RUN --mount=type=cache,target=/root/.npm \
    npm install -g pnpm@${PNPM_VERSION}

# Download dependencies as a separate step to take advantage of Docker's caching.
RUN --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=pnpm-lock.yaml,target=pnpm-lock.yaml \
    --mount=type=cache,target=/root/.local/share/pnpm/store \
    pnpm install --frozen-lockfile

# Copy the rest of the source files into the image.
COPY . .

# Expose the port the app runs on.
EXPOSE 3000

# Use development node environment by default.
ENV NODE_ENV development

# Start the application.
CMD ["pnpm", "run", "dev"]